name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Download Part 2
      run: Invoke-WebRequest https://download856.mediafire.com/4a6fcnknl1kgVcpNEu7SECKevvBUYzvGqGSeSJkgBORaswubQCqtvHTLV5fOCXfI2QTuujsJGgipKoNiZZzM6UMXRoGoMCW6kSpAi5rGZnMpIVaqsyrAtVojwpi3AxVT2wtbF-IJKSjlOPFuxZygueDfEjqJjJgIDwE6DdZqQCb3/5yexfegvmdglih2/RDP+tool+2024+Full.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "admin" -Password (ConvertTo-SecureString -AsPlainText "root" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
